
project_id = "szpdoihoxzlivothoyva"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://szpdoihoxzlivothoyva.supabase.co"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_phone_confirmations = false

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[edge-runtime]
enabled = true
port = 54326

[functions.facilities]
verify_jwt = false

[functions.app-api]
verify_jwt = false
