// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgbsegbhophveppwgxax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnYnNlZ2Job3BodmVwcHdneGF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3Mjg5MzYsImV4cCI6MjA2NjMwNDkzNn0.YFKVSoVPGcHpPI6KaOz4xAI-NnbcYuxjgNVt5k4Ij98";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);